name: integral_isolates
description: The power of Dart's compute function, but using a long lived isolate.
version: 0.5.1
repository: https://github.com/lohnn/integral_isolates
screenshots:
  - description: The integral_isolates logo.
    path: resources/icon.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.11.0
  meta: ^1.15.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.8
