name: integral_isolates
description: The power of Flutter's compute function, but using a long lived isolate.
version: 0.4.1
homepage: https://github.com/lohnn/integral_isolates

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  meta: ^1.9.1

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.6
