name: integral_isolates

packages:
  - packages/*

command:
  version:
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -c 1 -- flutter analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  doc:
    run: melos exec dart doc
    description: Run `dart doc` for all packages.

  format:
    run: melos exec flutter format .
    description: Run `flutter format` for all packages.

  test:select:
    run: melos exec -c 1 -- dart test
    description: Run `flutter test` for selected packages.
    select-package:
      dir-exists:
        - test

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.

  upgrade:
    run: melos exec -- flutter pub upgrade
    description: Upgrade to the latest supported versions of all packages.