name: integral_isolates
description: A sample command-line application.
version: 1.0.0
homepage: https://lohnn.se/

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  async: ^2.8.2
  meta: ^1.7.0

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.1
