include: package:lint/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning

linter:
  rules:
    - public_member_api_docs
    - curly_braces_in_flow_control_structures
    - flutter_style_todos
    - require_trailing_commas
    - unnecessary_lambdas
    - use_super_parameters
    - use_enums
    - use_colored_box
    - prefer_single_quotes
    - lines_longer_than_80_chars
