name: flame_isolate
description: Flame wrapper for Integral Isolates
version: 0.0.1
homepage: lohnn.se

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.3.0
  flutter:
    sdk: flutter
  integral_isolates:
    git: git@github.com:lohnn/integral_isolates.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

# The following section is specific to Flutter packages.
flutter:
