name: use_isolate_example
description: Example application for the use_isolate package
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  integral_isolates:
    path: ../../integral_isolates
  use_isolate:
    path: ..
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
