name: use_isolate_example
description: Example application for the use_isolate package
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  integral_isolates:
    path: ../../integral_isolates
  use_isolate:
    path: ..

dev_dependencies:
  lint: ^2.3.0

flutter:
  uses-material-design: true
