name: use_isolate_example
description: Example application for the use_isolate package
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  integral_isolates: ^0.5.1
  use_isolate: ^0.3.0+1

dev_dependencies:
  lint: ^2.3.0

flutter:
  uses-material-design: true
