name: use_isolate
description: A Hook wrapper of integral_isolates making multi-threading easy using hooks
version: 0.1.0
homepage: https://github.com/lohnn/integral_isolates

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  integral_isolates: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
