name: use_isolate
description: A Hook wrapper of integral_isolates making multi-threading easy using hooks
version: 0.3.0
homepage: https://github.com/lohnn/integral_isolates

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  integral_isolates: ^0.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
